from ..image_to_image.diffusion_clip_replicate import DiffusionClipReplicate
from ..image_to_image.jojogan_replicate import JojoganReplicate
from ..image_to_image.maxim_replicate import MaximReplicate
from ..image_to_image.stylecarigan_replicate import StylecariganReplicate
from ..image_to_image.stylegan_nada_replicate import StyleganNadaReplicate
