version: "3.9"
services:
  ml:
    build: .
    image: beverts312/bg-remover
    volumes:
      - ../../volumes/working:/home/mluser/working
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# TODO: Add volume for checkpoint